services:
  latex-ocr:
    build: .
    container_name: latex-ocr-app
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=0
    gpus: all
    volumes:
      - .:/app
      - ./checkpoints:/app/checkpoints
      - ./demo:/app/demo
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "app/streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]

  train:
    build: .
    container_name: latex-ocr-train
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=0
    gpus: all
    volumes:
      - .:/app
      - ./checkpoints:/app/checkpoints
      - ./demo:/app/demo
    command: ["python", "-m", "src.train", "--config", "configs/train_config.qwen2vl_2b.yaml", "--run_name", "qwen2vl_latex_only"]
